### ISSUE TITLE
Support for New API version from Foursquare (2014 update)

### ISSUE THREAD

**Issue by shaikhsohail30** [mLewisLogic/foursquare#59]
Hi 

As per the URL below

https://developer.foursquare.com/docs/2014update

It is mentioned that there would be some impact on existing applications using Foursquare's current API. After the new API is ready for use some features might be deprecated. Please could you guide us on whether there will be any updates to this python package.

**Comment by mLewisLogic** [comment]
Just update to latest API version (`20150201`) and all specs are passing for existing endpoints. I'd consider this up-to-date.

If there are new endpoints that you need, feel free to add them.
