### ISSUE TITLE
Pip package version

### ISSUE THREAD

**Issue by kontur** [mLewisLogic/foursquare#62]
Hey,

I noticed that for me installing from pip fetches an outdated version of the library, so I defaulted to pip install from a git commit - would it be possible to update the version available via pip, surely this might confuse other users as well, when they try use features documented here, but not available in the latest version installed via pip?

Thanks for the great package :)

**Comment by mLewisLogic** [comment]
@kontur Interesting. What version are you seeing?
Are you not seeing `2014.04.23a`?

This should be the latest:
https://pypi.python.org/pypi?:action=display&name=foursquare&version=2014.04.23a

Versions are based upon the requested API version, not necessarily the release date of the library. They often coincide, but not necessarily.

**Comment by mLewisLogic** [comment]
Just bumped the API/package version to `2015.02.01` (after running specs) to avoid confusion.

**Comment by mLewisLogic** [comment]
If this fixes things on your end, feel free to close this issue.

**Comment by kontur** [comment]
Hey,

thanks for looking into this.

When I setup a new virtualenv now and install I get the following:

    (venv)Johanness-MacBook-Pro:test johannes$ pip list
    foursquare (20130707)
    httplib2 (0.9)
    pip (1.5.6)
    poster (0.8.1)
    setuptools (3.6)
    wsgiref (0.1.2)

This seems to be the same version number I got when originally reporting the issue, so nothing has changed. Is there some sort of version caching that pip does that could prevent it from fetching the latest?

**Comment by mLewisLogic** [comment]
Thanks for the bug report @kontur.
K, it looks like it's a known `pip` issue that it will install the package with the highest semantic version, even if it's explicitly hidden on PyPi.

I changed the version scheme so that the latest version is explicitly greater than all prior (even old, hidden) versions.

The latest should be `1!2015.2.1`.

**Comment by kontur** [comment]
Hey, ah okay, that could explain it.

When I now create a new folder, virtualenv and then install `foursquare` via pip I still do get the same version *foursquare (20130707)*.
When after install I check `pip search foursquare` I get amongst other hits:

    foursquare                - easy-as-pie foursquare wrapper library
    INSTALLED: 20130707 (latest)

Does pip take a while to update its caches or something until it actually matches the version listed on https://pypi.python.org/pypi?:action=display&name=foursquare ?

**Comment by mLewisLogic** [comment]
Interesting.

I opened [an issue](https://github.com/pypa/pip/issues/2391) on `pip`, so hopefully we can get this sorted shortly.

Thanks for the patience.

**Comment by mLewisLogic** [comment]
K, looks like it's an issue with `pip`. Next version of `pip` should return the latest version.

**Comment by mLewisLogic** [comment]
I'm going to leave this open until the `pip` team cuts a release.

**Comment by kontur** [comment]
Great :)

For reference until the latest version gets installed from pip, I leave here the way I used pip to install the latest version via git:

    $ pip install git+https://github.com/mLewisLogic/foursquare.git

This should add the repo diretly as reference and install with pip.

**Comment by mLewisLogic** [comment]
Looks like this is fixed with `pip 6.0.8`!

**Comment by mLewisLogic** [comment]
For future explorers who find this issue, just upgrade pip using:

`pip install pip --upgrade`

You may or may not need sudo, depending upon your specific setup.

**Comment by kontur** [comment]
Perfect. Can confirm this installs right now. Thanks for the effort :)
