### ISSUE TITLE
Error when I seach with accents

### ISSUE THREAD

**Issue by davjimvar** [mLewisLogic/foursquare#67]
I'm using venues/explore and parameter near is a city with accents, then the library returns me error coding.
Exactly:
client.venues.explore(params={'near': city, 'section': section, 'limit': limit})
Where city is málaga.

The error is: 
FailedGeocode: Couldn't geocode param near: m\ufffdlaga

**Comment by mLewisLogic** [comment]
Is `city` of type `Unicode`?

**Comment by mLewisLogic** [comment]
The tests definitely include unicode characters:
https://github.com/mLewisLogic/foursquare/blob/master/foursquare/tests/test_venues.py#L33

**Comment by davjimvar** [comment]
Yes, city is unicode.
I will run the tests again

**Comment by mLewisLogic** [comment]
@davjimvar did you figure out what the issue is?
