### ISSUE TITLE
foursquare venue stats missing

### ISSUE THREAD

**Issue by ivancruzbht** [mLewisLogic/foursquare#68]
The retrieved venue stats are quite different from the described in the foursquare API docs

https://developer.foursquare.com/docs/responses/venuestats.

The response I receive is something like this:
{u'tipCount': 164, u'checkinsCount': 5039, u'visitsCount': 5039, u'usersCount': 2688}

Lots of fields are missing, and I am interested in retrieve the "recentVisitors" param of the venue stats request

I am doing auth without the access token (i.e. im just using my client id and secret). Does this might the cause of getting a different response? Or is this feature missing?

Thanks!

**Comment by mLewisLogic** [comment]
I'm going to guess that it has to do with how you're authing.
I'd suggest asking in Foursquare's developer forums. I don't know the inner workings of how their API makes decisions like that.
