### ISSUE TITLE
Files are read twice when foursquare is imported

### ISSUE THREAD

**Issue by mgarod** [mLewisLogic/foursquare#72]
I have a file called 'test':
```
line1
line2
```
I have some code, main.py:
```
# import foursquare

with open('test') as f:
  one, two = [l.strip() for l in f.readlines()]

print(one)
print(two)
```
When the line 'import foursquare' is not present in the file, output is what you'd expect:
```
line1
line2
```
But when the line 'import foursquare' is present, the output is:
```
line1
line2
line1
line2
```

Anyone have an idea why this is? I'm using python 3.5.1

**Comment by mgarod** [comment]
I set up a brand new virtual environment and the error persists.

**Comment by mLewisLogic** [comment]
I'm not able to repro this.

**Comment by mLewisLogic** [comment]
Are you running on latest version?

Given that I can't repro with the above steps, there's not too much I can do.
If this is still giving you issues and you come up with a fix I'd be happy to merge in a PR.
