### ISSUE TITLE
Why it does not return what I see on Foursquare

### ISSUE THREAD

**Issue by maelfosso** [mLewisLogic/foursquare#74]
Hi,

I don't understand something
I tried to get all my friend. Now I have 19 friends but the api just return me 10 why ?
And It's the samething with the friends of mine, I don't have the exact number of friend I see on Foursquare.

The second problem, it's the structure of the response, the structure is not the same all the time. Could you explain why please ?

Thanks

**Comment by mLewisLogic** [comment]
Can you please include detailed requests and responses?

**Comment by mLewisLogic** [comment]
Also, have you compared results with the API Explorer on foursquare's developer site?
