### ISSUE TITLE
AttributeError: module 'foursquare' has no attribute 'Foursquare'

### ISSUE THREAD

**Issue by burakgulmez** [mLewisLogic/foursquare#84]
"AttributeError: module 'foursquare' has no attribute 'Foursquare'"
I get this error every time.
I use python 3.

My code:
```
import foursquare
#from foursquare import Foursquare , <--- I tried this but it doesnt work
client_id="..."
client_secret="..."
client = foursquare.Foursquare(client_id=client_id, client_secret=client_secret)
```

**Comment by mLewisLogic** [comment]
I just tested it with the following process:

```sh
mkdir test_foursquare
cd test_foursquare
virtualenv -p python3.6 .
source bin/activate
pip install foursquare
python
```

```python
>>> from foursquare import Foursquare
>>> Foursquare.__doc__
'foursquare V2 API wrapper'
```

Seems like it might be an issue with your environment.

**Comment by mLewisLogic** [comment]
I'm going to close this for now.
If you can repro your error in a contained and repeatable script, reply here with it and I'll re-open and look into a fix.

**Comment by burakgulmez** [comment]
I got the same resulte
```
>>> from foursquare import Foursquare
>>> Foursquare.__doc__
'foursquare V2 API wrapper'
```

**Comment by burakgulmez** [comment]
I solved the problem.
That was a big mistake :)
The script name was "foursquare", then i renamed and the problem was solved.
