### ISSUE TITLE
venues.herenow() doesnt show the user list

### ISSUE THREAD

**Issue by burakgulmez** [mLewisLogic/foursquare#85]
venues.herenow() shows only how many people is at this place. It doesnt show the people liste.
Sample code:
```python
client.checkins.add(params={"venueId":"...","broadcast":"public"}) 
print(client.venues("...")["venue"]["name"], client.venues.herenow("...")) 
print(client.checkins.recent()) # to control check in
```
Output only gives venue name, a number(how many people) and a null list
Also I controlled the check in, yes it was successful.

**Comment by mLewisLogic** [comment]
The package leaves responses pretty intact. If you're getting the rest of the response, its likely a limitation of the API. Maybe try turning on DEBUG logging to see what traffic is going out and coming back? It might help you figure out what 4sq is actually returning.
