### ISSUE TITLE
Can we get a new PyPI release?

### ISSUE THREAD

**Issue by jacebrowning** [mLewisLogic/foursquare#89]
It appears to be a couple years since the last release, but there are newer commits.

Additionally the `1!2016.9.12` format does not appear to be compatible with [PEP 440](https://www.python.org/dev/peps/pep-0440/).

**Comment by kngspook** [comment]
Also came here to ask for this. 👍

**Comment by mLewisLogic** [comment]
I believe it does comply with [Public version identifiers](https://www.python.org/dev/peps/pep-0440/#id22).

I'll def cut a release though. Excited to see some interest in Foursquare again.

What are the you all working on? (if it's not top secret)

**Comment by mLewisLogic** [comment]
Ahhh, you're right!
```
UserWarning: Normalizing '1!2016.09.12' to '1!2016.9.12'
```
Gotta drop that `0`.

**Comment by mLewisLogic** [comment]
There we are.
https://pypi.org/project/foursquare/1!2019.2.12/

Let me know if you run into any issues.

**Comment by jacebrowning** [comment]
Thanks for the release! I'm working on an app to recommend restaurants based on least-recent checkin.

---

This is unfortunately not working with [Poetry](https://poetry.eustace.io/). It installed the wrong version:

```
$ poetry new demo
$ cd demo
$ poetry add "foursquare==1\!2019.2.12"
Creating virtualenv demo-py3.7 in /private/tmp/demo/.venv

Updating dependencies
Resolving dependencies... (0.2s)
Package operations: 13 installs, 0 updates, 0 removals

Writing lock file

  - Installing certifi (2018.11.29)
  ...
  - Installing foursquare (1!2015.2.1)
  ...
```

I suppose this is probably a bug on Poetry's side.

**Comment by mLewisLogic** [comment]
Hrmm, could be the case.
The epoch prefix is a little ugly, but was the best standards-compliant way I could get the latest releases to follow a general semantic versioning while still looking like "latest" compared with some old legacy versions that were cut in a `yyyymmdd` format.
