### ISSUE TITLE
 Error connecting with foursquare API

### ISSUE THREAD

**Issue by wonderfulvamsi** [mLewisLogic/foursquare#91]
while trying to connect I'm encountering the following error

 : HTTPSConnectionPool(host='api.foursquare.com', port=443): Max retries exceeded with url: /v2/venues/40a55d80f964a52020f31ee3?v=20190216&client_id=PC0W23LXG00OY3H5QOV4S3WZIZG0MQEZUDYZKLB5N00AYX21&client_secret=HU31OWG0NR4TXZF514AM5N2B15HEAJJUYZJFSPHFUM30YDW2 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x1077F2D0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

**Comment by mLewisLogic** [comment]
It's working for me. Check your network settings.

You should revoke that key. You just published your secret key, which will allow anybody who reads this issue to impersonate your account.
