### ISSUE TITLE
Add support for claiming venues

### ISSUE THREAD

**Issue by milind-shakya-sp** [mLewisLogic/foursquare#93]
https://developer.foursquare.com/docs/api/venues/claim

**Comment by mLewisLogic** [comment]
Cool, thanks for the report.
Make a PR with tests and I'll get it reviewed and merged.

**Comment by milind-shakya-sp** [comment]
@mLewisLogic https://github.com/mLewisLogic/foursquare/pull/94 thanks.

**Comment by mLewisLogic** [comment]
Your venue claim method is now included in the latest version of the library.
https://pypi.org/project/foursquare/1!2020.1.30/

**Comment by milind-shakya-sp** [comment]
@mLewisLogic 👍
