### ISSUE TITLE
'ModuleNotFoundError' when importing in a new virtualenv only through VS Code

### ISSUE THREAD

**Issue by Naderart** [mLewisLogic/foursquare#97]
Traceback (most recent call last):
  File "/home/nader/envs/fsq/b3.py", line 4, in <module>
    import foursquare
ModuleNotFoundError: No module named 'foursquare'

The above error only happens when I try to import foursquare in Visual Studio Code, I can't figure out why.
I start a terminal inside VS Code and activate my virtualenv, then run the code with the shortcut 'Shift+Enter'. it returns this error.
While if I start a python interpreter inside the same VS Code terminal, with the same virtualenv activated, it imports the module without any errors.
Python: 3.6
OS: Ubuntu 18.04.4 LTS
VS Code version: 1.46.1

snapshot of **'pip list'** command inside my virtualenv :
Package    Version
certifi    2020.4.5.2
chardet    3.0.4
**foursquare 1!2020.1.30**
idna       2.9
pip        20.1.1
requests   2.24.0
setuptools 47.3.1
six        1.15.0
urllib3    1.25.9
wheel      0.34.2

**Comment by mLewisLogic** [comment]
Sorry, I don't know much about VSCode. Seems like an IDE specific issue if it is working within a Python interpreter.

**Comment by mLewisLogic** [comment]
If you can reproduce the issue inside of a venv from the command line, let me know the commands run to repro.

**Comment by Naderart** [comment]
> If you can reproduce the issue inside of a venv from the command line, let me know the commands run to repro.

Works perfectly in the command line, seems to only happen inside the IDE, same issue with BeautifulSoup too, couldn't solve it until I pip-installed the module on my main python site-packages, which isn't a good solve of course. Looks like I'm going to search for another IDE. Thank you very much for replying though.
